property_groups:
  - group_name: "General Information"
    properties:
      - name: "document_title"
        description: "The title of the document."
        validation:
          required: true
      - name: "isin"
        description: "The ISIN (International Securities Identification Number) of the financial product."
        validation:
          required: true
          regex: "^[A-Z]{2}[A-Z0-9]{9}[0-9]{1}$"
  - group_name: "Risk Factors"
    properties:
      - name: "main_risks"
        description: "The primary risk factors associated with this investment, as listed in the document."
        validation:
          required: false
  - group_name: "Document Classification"
    properties:
      - name: "document_type"
        description: "The classification of the document, for example: Prospectus, Key Information Document (KID), Annual Report, or Other."
        validation:
          required: true
          enum: ["Prospectus", "KID", "Annual Report", "Other"]
