[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cosmos-init-service"
version = "0.1.0"
description = "Cosmos DB initialization microservice for risk analytics"
authors = [
    {name = "Risk Analytics Team"}
]
dependencies = [
    "azure-cosmos>=4.5.0",
    "azure-identity>=1.12.0",
    "pydantic>=2.0.0",
    "pydantic-settings>=2.0.0",
    "news-sentiment-common",
]
requires-python = ">=3.11"

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-asyncio>=0.21.0",
    "pytest-mock>=3.10.0",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-dir]
"" = "src" 