# Risk Analytics Agent Application Configuration

# API configuration
api:
  host: "0.0.0.0"
  port: 8000
  debug: false
  cors_origins:
    - "http://localhost:3000"
    - "https://example.com"

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "risk-analytics.log"

# Feature store configuration
feature_store:
  cache_ttl: 3600  # seconds
  use_redis_cache: true
  
  # Redis configuration
  redis:
    host: "localhost"
    port: 6379
    db: 0
    password: ""  # Empty for no password
    
  # Pinot configuration
  pinot:
    controller: "localhost:9000"
    broker: "localhost:8099"

# Kafka configuration
kafka:
  bootstrap_servers: "localhost:9092"
  topics:
    market_data: "market-data-fixed-income"
    trade_events: "trade-events"
  group_id: "risk-analytics-consumer"
  auto_offset_reset: "earliest"

# Security configuration
security:
  auth_algorithm: "HS256"
  access_token_expire_minutes: 30

# Model serving configuration
model_serving:
  port: 8001
  registry_path: "./models"
  model_paths:
    tft: "models/regime_model/tft_model.pt"
    nbeats: "models/risk_model/nbeats_model.pt"
    deepar: "models/risk_model/deepar_model.pt" 
