# Event Type Weights (W_event)
# These weights reflect the asymmetric impact of market events on fixed-income instruments
# as defined in the business requirements

event_weights:
  Default: 20.0                      # A failure to meet a debt obligation. The most severe credit event.
  Bankruptcy: 18.0                   # A legal declaration of inability to pay debts.
  Credit_Rating_Downgrade: 15.0      # A reduction in credit rating by a major agency. The impact is severe and often triggers forced selling.
  Bond_Insurer_Downgrade: 12.0       # A downgrade of a major bond insurer, affecting the perceived safety of insured securities.
  Central_Bank_Policy: 9.0           # Announcements related to monetary policy (e.g., interest rate changes).
  State_Budget_Crisis: 9.0           # For MUNI bonds, a significant state budget shortfall or fiscal emergency.
  Natural_Disaster_Impact: 8.0       # For MUNI bonds, a major natural disaster impacting the tax base or a specific project's revenue stream.
  M&A_Announced: 7.0                 # Announcement of a merger or acquisition. Note: The actual sentiment score must be nuanced.
  Pension_Funding_Status_Change: 7.0 # For MUNI bonds, significant news about the underfunding or improved funding of public pension liabilities.
  Credit_Outlook_Negative: 6.0       # A rating agency's indication that a future downgrade is possible.
  Regulatory_Investigation: 6.0       # An official investigation into an issuer's practices.
  Macro_Economic_Data: 6.0           # Major economic releases (e.g., CPI, GDP, Jobs Report).
  Credit_Rating_Upgrade: 5.0         # An improvement in credit rating. The impact is less pronounced and often priced in earlier than downgrades.
  Guidance_Change: 5.0               # A change in the company's forward-looking financial guidance.
  Lawsuit_Filed: 5.0                 # A significant lawsuit filed against the issuer. Impact can vary and score must reflect the severity.
  Credit_Outlook_Positive: 4.0       # An indication that a future upgrade is possible.
  Earnings_Miss: 4.0                 # Reported earnings that are below analyst expectations.
  Earnings_Beat: 3.0                 # Reported earnings that are above analyst expectations.
  Executive_Change: 2.0              # A change in a key executive position (e.g., CEO, CFO).
  General_News: 1.0                  # A baseline weight for news that does not fit into a more specific category. 