# Source Credibility Weights (W_source)
# These weights reflect the credibility and authority of different news sources
# as defined in the business requirements

source_weights:
  TIER_1_REGULATOR: 1.5       # SEC, Moody's, S&P - Highest credibility regulatory sources
  TIER_2_PREMIUM_FINANCIAL: 1.2  # Bloomberg, Wall Street Journal - Premium financial news
  TIER_3_GENERAL_FINANCIAL: 1.0  # Other reputable financial news sources - Baseline weight
  TIER_4_COMPANY_PR: 0.8      # Official press releases from the issuer - Lower weight due to bias
  TIER_5_SYNDICATED: 0.6      # Syndicated news wires, less reputable sources - Lowest weight 