version_: 1
template_: SimpleKGPipeline

# Core behavior
from_pdf: false
perform_entity_resolution: true

# Text splitter: 300 tokens with 50 overlap
text_splitter:
  class_: text_splitters.fixed_size_splitter.FixedSizeSplitter
  params_:
    chunk_size: 300
    chunk_overlap: 50

neo4j_database: neo4j

# Neo4j connection
neo4j_config:
  params_:
    uri:
      resolver_: ENV
      var_: NEO4J_URI
    user:
      resolver_: ENV
      var_: NEO4J_USERNAME
    password:
      resolver_: ENV
      var_: NEO4J_PASSWORD
  neo4j_database:
    resolver_: ENV
    var_: NEO4J_DATABASE

# LLM configuration (OpenAI)
llm_config:
  class_: OpenAILLM
  params_:
    model_name:
      resolver_: ENV
      var_: OAI_MODEL
    api_key:
      resolver_: ENV
      var_: OAI_KEY
    base_url:
      resolver_: ENV
      var_: OAI_BASE_URL
    model_params:
      temperature: 0

# Embedder configuration (OpenAI embeddings)
embedder_config:
  class_: OpenAIEmbeddings
  params_:
    model:
      resolver_: ENV
      var_: OAI_EMBED_MODEL
    api_key:
      resolver_: ENV
      var_: OAI_KEY
    base_url:
      resolver_: ENV
      var_: OAI_BASE_URL

# Vector index configuration (used by ensure_vector_index)
vector_index:
  name: chunk_embeddings
  label: Chunk
  property: embedding
  dimensions: 1536
  similarity: cosine

# Community summaries vector index (ensured by pipeline)
community_vector_index:
  name: community_summary_idx
  label: __Community__
  property: summary_embedding
  dimensions: 1536
  similarity: cosine

# Optional: provide schema guidance (defaults to automatic extraction if omitted)
schema:
  node_types:
    # Core
    - PROJECT
    - DOCUMENT
    - FILE
    - REQUIREMENT
    - ENTITY
    # Trading/Markets
    - ORDER
    - TRADE
    - INSTRUMENT
    - EQUITY
    - BOND
    - DERIVATIVE
    - OPTION
    - FUTURE
    - SWAP
    - FX_PAIR
    - PORTFOLIO
    - STRATEGY
    - ALPHA_MODEL
    - RISK_MODEL
    - BENCHMARK
    - INDEX
    - ETF
    - FUND
    - BROKER
    - EXCHANGE
    - VENUE
    - DARK_POOL
    - ORDER_BOOK
    - QUOTE
    - TICKER
    - BAR
    - DEPTH
    - AUCTION
    - CCP
    - CSD
    - CLEARING_MEMBER
    - MARGIN_CALL
    - SETTLEMENT_INSTRUCTION
    - CASH_MOVEMENT
    - CORPORATE_ACTION
    - DIVIDEND
    - SPLIT
    - MERGER
    - RATING
    - RATING_AGENCY
    - ANALYST_REPORT
    - PROSPECTUS
    - TERM_SHEET
    - REFERENCE_DATA
    - FIGI
    - ISIN
    - CUSIP
    - RIC
    - BLOOMBERG_FIELD
    - REUTERS_FIELD
    - CALENDAR
    - HOLIDAY
    - CURRENCY
    - COUNTRY
    - REGION
    # Wealth/Client
    - CLIENT
    - ACCOUNT
    - RELATIONSHIP
    - ADVISOR
    - MANDATE
    - MODEL_PORTFOLIO
    - REBALANCE
    - FEE_SCHEDULE
    - GOAL
    - SUITABILITY_PROFILE
    - RISK_TOLERANCE
    - KYC_PROFILE
    - AML_ALERT
    # Risk/Reg/Reporting
    - VaR_REPORT
    - STRESS_TEST
    - LIMIT
    - BREACH
    - CONTROL
    - CONTROL_TEST
    - POLICY
    - PROCEDURE
    - MI_FID_REPORT
    - FINRA_REPORT
    - AUDIT
    - FINDING
    - REMEDIATION
    - ISO20022_MESSAGE
    - SWIFT_MESSAGE
    - PAYMENT
    - LEDGER_ENTRY
    - GL_ACCOUNT
    # Data/Platform/IT
    - SERVICE
    - API
    - MICROSERVICE
    - EVENT
    - TOPIC
    - QUEUE
    - ETL_JOB
    - BATCH
    - DATA_PIPELINE
    - DAG
    - DATA_CATALOG
    - DATA_LAKE
    - DATA_WAREHOUSE
    - TABLE
    - COLUMN
    - SCHEMA_VERSION
    - NOTEBOOK
    - DASHBOARD
    - REPORT
    - KPI
    - ALERT
    - INCIDENT
    - TICKET
    - CHANGE_REQUEST
    - DEPLOYMENT
    - RELEASE
    - FEATURE_FLAG
    - SECRET
    - VAULT
    - KEY
    - CERTIFICATE
    - IAM_ROLE
    - USER
    - GROUP
    - TENANT
    - ENVIRONMENT
    - NAMESPACE
    - CLUSTER
    - NODE_HOST
    - POD
    - CONTAINER
    - IMAGE
    - REPOSITORY
    - COMMIT
    - CI_JOB
    - CD_PIPELINE
    - TEST_SUITE
    - TEST_CASE
    - COVERAGE
    - LOG
    - METRIC
    - TRACE
    - CONFIG
    - FEATURE_TOGGLE
    - MONITOR
    - SLO
    - SLA
    - SYNTHETIC_CHECK
    - CONNECTOR
    - INGESTION_JOB
    - TRANSFORM_JOB
    - LOAD_JOB
    # Organizations
    - COMPANY
    - SUBSIDIARY
    - COUNTERPARTY
    - CUSTODIAN
    - ADMINISTRATOR
    - PRIME_BROKER
    - MARKET_DATA_FEED
    - NEWS_FEED
  relationship_types:
    # Core chain
    - PROJECT_HAS_DOCUMENT
    - PROJECT_HAS_FILE
    - DOCUMENT_HAS_REQUIREMENT
    - FILE_INCLUDES_REQUIREMENT
    - REQUIREMENT_IS_INCLUDED_IN_FILE
    - REQUIREMENT_MENTIONS_ENTITY
    - ENTITY_RELATES_TO_ENTITY
    - ENTITY_SUPPORTS_REQUIREMENT
    # Trading flows
    - TRADES_ON
    - ROUTES_VIA
    - EXECUTED_AT
    - CLEARED_BY
    - SETTLED_AT
    - CUSTODIED_BY
    - ALLOCATED_TO
    - HEDGES
    - OWNS
    - BENCHMARKED_BY
    - FOLLOWS_STRATEGY
    - RUNS_MODEL
    - CALCULATED_BY
    - VALUED_BY
    # Market data
    - HAS_TICKER
    - HAS_QUOTE
    - HAS_BAR
    - HAS_ORDER_BOOK
    - PUBLISHES
    - SUBSCRIBES
    - INGESTS
    # Wealth
    - MANAGED_BY
    - ADVISED_BY
    - BELONGS_TO
    - HAS_MANDATE
    - USES_MODEL_PORTFOLIO
    - USED_BY
    - REBALANCED_BY
    - FEES_DETERMINED_BY
    - SUITABILITY_ASSESSED_BY
    # Risk/Reg
    - COMPLIES_WITH
    - VIOLATES
    - REPORTS_TO
    - FILES_WITH
    - LIMIT_OF
    - BREACHED_BY
    - TESTED_BY
    - CONTROLS
    - FINDING_OF
    - REMEDIATES
    # Data/IT
    - DEPENDS_ON
    - CALLS
    - EMITS
    - CONSUMES
    - PRODUCES
    - RUNS_ON
    - DEPLOYED_TO
    - MONITORED_BY
    - ALERTS_ON
    - LOGS_TO
    - TRACES_TO
    - CONFIGURES
    - PARAMETER_OF
    - VERSION_OF
    - SUPERSEDES
    - ENRICHED_BY
    - SOURCED_FROM
    - MAPS_TO
    - TRANSFORMS_TO
    - LOADS_TO
    - SECURED_BY
    - ENCRYPTED_BY
    - AUTHENTICATED_BY
    - AUTHORIZED_BY
    # Finance ops
    - RESULTS_IN
    - CORPORATE_ACTION_OF
    - PAYS
    - RECEIVES
    - POSTED_TO
    - NETTED_BY
  patterns:
    - ["PROJECT", "PROJECT_HAS_DOCUMENT", "DOCUMENT"]
    - ["PROJECT", "PROJECT_HAS_FILE", "FILE"]
    - ["DOCUMENT", "DOCUMENT_HAS_REQUIREMENT", "REQUIREMENT"]
    - ["FILE", "FILE_INCLUDES_REQUIREMENT", "REQUIREMENT"]
    - ["REQUIREMENT", "REQUIREMENT_IS_INCLUDED_IN_FILE", "FILE"]
    - ["REQUIREMENT", "REQUIREMENT_MENTIONS_ENTITY", "ENTITY"]
    - ["ENTITY", "ENTITY_RELATES_TO_ENTITY", "ENTITY"]
    # Representative finance/IT links
    - ["ORDER", "TRADES_ON", "VENUE"]
    - ["TRADE", "EXECUTED_AT", "EXCHANGE"]
    - ["TRADE", "CLEARED_BY", "CCP"]
    - ["TRADE", "SETTLED_AT", "CSD"]
    - ["PORTFOLIO", "BENCHMARKED_BY", "BENCHMARK"]
    - ["CLIENT", "MANAGED_BY", "ADVISOR"]
    - ["ACCOUNT", "BELONGS_TO", "CLIENT"]
    - ["MODEL_PORTFOLIO", "USED_BY", "ACCOUNT"]
    - ["SERVICE", "DEPENDS_ON", "SERVICE"]
    - ["MICROSERVICE", "CALLS", "API"]
    - ["ETL_JOB", "PRODUCES", "TABLE"]
    - ["CONNECTOR", "INGESTS", "REFERENCE_DATA"]
  additional_node_types: true
  additional_relationship_types: true
  additional_patterns: true
  additional_properties: true

