apiVersion: batch/v1
kind: Job
metadata:
  name: neo4j-schema-init
  namespace: agentic-ai
spec:
  template:
    spec:
      containers:
        - name: schema-init
          volumeMounts:
            - name: secrets-store
              $patch: delete
      volumes:
        - name: secrets-store
          $patch: delete


