apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-tasks-service
  namespace: agentic-ai
spec:
  template:
    spec:
      containers:
        - name: ai-tasks-service
          volumeMounts:
            - name: secrets-store
              $patch: delete
      volumes:
        - name: secrets-store
          $patch: delete


