[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "benzinga-adapter"
version = "0.1.0"
description = "Benzinga data ingestion adapter for the News Sentiment Service"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]",
    "httpx",
    "python-dotenv",
    "azure-appconfiguration-provider",
    "azure-identity",
    "beautifulsoup4",
    "pydantic-settings",
    "news_sentiment_common @ file:../../../common"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-asyncio"
]

[tool.pytest.ini_options]
pythonpath = [
    "src"
]

[tool.setuptools.packages.find]
where = ["src"]
exclude = ["tests*"] 