"""Shared constants package."""

from .streams import (
    UI_CHANNEL_PREFIX,
    UI_PROJECT_PROGRESS_NAME,
    UI_PROJECT_PROGRESS_CHANNEL,
)
from .pipelines import (
    APP_NAME_DOCUMENT_PROCESSING,
    APP_NAME_NEO4J_INGESTION,
    APP_NAME_PROJECT_MANAGEMENT,
    QUEUE_DOCUMENT_PROCESSING,
    QUEUE_NEO4J_INGESTION,
    QUEUE_NEO4J_INGESTION_DLQ,
    ROUTE_DOCUMENT_TASKS_PATTERN,
    ROUTE_NEO4J_TASKS_PATTERN,
    TASK_PROCESS_PROJECT_DOCS,
    TASK_RUN_GRAPHRAG_JOB,
    EXPECTED_TASKS_DOCUMENT,
    EXPECTED_TASKS_INGESTION,
    GATE_NS_DOCS,
    GATE_NS_INGESTION,
    GATE_DEFAULT_RUNNING_TTL,
    GATE_DEFAULT_PENDING_TTL,
    GATE_DEFAULT_COALESCE_TTL,
)

__all__ = [
    "UI_CHANNEL_PREFIX",
    "UI_PROJECT_PROGRESS_NAME",
    "UI_PROJECT_PROGRESS_CHANNEL",
    # Pipelines
    "APP_NAME_DOCUMENT_PROCESSING",
    "APP_NAME_NEO4J_INGESTION",
    "APP_NAME_PROJECT_MANAGEMENT",
    "QUEUE_DOCUMENT_PROCESSING",
    "QUEUE_NEO4J_INGESTION",
    "QUEUE_NEO4J_INGESTION_DLQ",
    "ROUTE_DOCUMENT_TASKS_PATTERN",
    "ROUTE_NEO4J_TASKS_PATTERN",
    "TASK_PROCESS_PROJECT_DOCS",
    "TASK_RUN_GRAPHRAG_JOB",
    "EXPECTED_TASKS_DOCUMENT",
    "EXPECTED_TASKS_INGESTION",
    "GATE_NS_DOCS",
    "GATE_NS_INGESTION",
    "GATE_DEFAULT_RUNNING_TTL",
    "GATE_DEFAULT_PENDING_TTL",
    "GATE_DEFAULT_COALESCE_TTL",
]