"""Shared Redis Streams constants."""

UI_CHANNEL_PREFIX = "ui"
UI_PROJECT_PROGRESS_NAME = "project_progress"
UI_PROJECT_PROGRESS_CHANNEL = f"{UI_CHANNEL_PREFIX}:{UI_PROJECT_PROGRESS_NAME}"
UI_AI_WORKFLOW_PROGRESS_NAME = "ai_workflow_progress"
UI_AI_WORKFLOW_PROGRESS_CHANNEL = f"{UI_CHANNEL_PREFIX}:{UI_AI_WORKFLOW_PROGRESS_NAME}"
UI_AI_TASKS_PROGRESS_NAME = "ai_tasks_progress"
UI_AI_TASKS_PROGRESS_CHANNEL = f"{UI_CHANNEL_PREFIX}:{UI_AI_TASKS_PROGRESS_NAME}"
