apiVersion: v1
kind: ConfigMap
metadata:
  name: agentic-ai-config
  namespace: agentic-ai
data:
  ENVIRONMENT: "${ENVIRONMENT}"
  PROJECT_NAME: "agentic-ai"
  # App Configuration connection will be handled via Workload Identity
  APP_CONFIG_ENDPOINT: "https://agentic-ai-${ENVIRONMENT}-appconfig.azconfig.io"
  
  # Logging configuration
  LOG_LEVEL: "INFO"
  
  # API Configuration
  API_VERSION: "v1"
  
  # Database configuration (secrets will be loaded from App Configuration)
  POSTGRES_HOST: "agentic-ai-${ENVIRONMENT}-psql.postgres.database.azure.com"
  POSTGRES_PORT: "5432"
  
  # Redis configuration (if using)
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379" 