apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: agentic-ai-app

# List of resource files to include
resources:
  - namespace.yaml
  - service-account.yaml
  - configmap.yaml
  - project-management-service.yaml

# Common labels applied to all resources
commonLabels:
  project: agentic-ai
  managed-by: kustomize

# Images to be replaced during deployment
images:
  - name: project_management_service
    newName: ${DOCKER_REGISTRY}/${CI_PROJECT_PATH}/project_management_service
    newTag: ${DOCKER_IMAGE_TAG}

# Configuration transformations
patchesStrategicMerge: []

# Environment-specific configurations
patchesJson6902: []

# Replace placeholders with actual values
replacements:
  - source:
      kind: ConfigMap
      name: agentic-ai-config
      fieldPath: data.ENVIRONMENT
    targets:
      - select:
          kind: Namespace
          name: agentic-ai
        fieldPaths:
          - metadata.labels.environment

# Generate additional resources
generators: []

# Namespace for all resources
namespace: agentic-ai 