apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-management-service
  namespace: agentic-ai
  labels:
    app: project-management-service
    component: api
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project-management-service
  template:
    metadata:
      labels:
        app: project-management-service
        component: api
        tier: backend
    spec:
      serviceAccountName: agentic-ai-workload-identity
      containers:
      - name: project-management-service
        image: ${DOCKER_REGISTRY}/${CI_PROJECT_PATH}/project_management_service:${DOCKER_IMAGE_TAG}
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: agentic-ai-config
              key: ENVIRONMENT
        - name: APP_CONFIG_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: agentic-ai-config
              key: APP_CONFIG_ENDPOINT
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: agentic-ai-config
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: agentic-ai-config
              key: POSTGRES_PORT
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: project-management-service
  namespace: agentic-ai
  labels:
    app: project-management-service
    component: api
    tier: backend
spec:
  selector:
    app: project-management-service
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  type: ClusterIP 