# Configuration placeholder 

# TFT Regime Model Configuration

# Data parameters
data:
  max_encoder_length: 60  # Number of time steps used as encoder inputs
  max_prediction_length: 1  # Number of time steps to predict into future
  time_idx: "time_idx"  # Column name for time index
  group_ids:  # Column(s) for grouping data
    - "security_id"
  target: "regime"  # Target variable to predict
  
  # Variables configuration
  categorical_variables:
    - "market_type"
    - "security_type"
  continuous_variables:
    - "price"
    - "volume"
    - "volatility"
    - "credit_spread"
    - "liquidity_metric"
    - "rate_change"
  static_variables:
    - "security_type"
  time_varying_known_variables:
    - "time_idx"
  time_varying_unknown_variables:
    - "price"
    - "volume"
    - "volatility"
    - "credit_spread"
    - "liquidity_metric"
    - "rate_change"

# TFT model parameters
model:
  hidden_size: 64
  attention_head_size: 4
  dropout: 0.1
  hidden_continuous_size: 32
  cell_type: "LSTM"  # LSTM or GRU
  
  # Training parameters
  learning_rate: 0.001
  batch_size: 64
  max_epochs: 100
  early_stopping_patience: 10
  gradient_clip_val: 0.1

  # Loss function
  loss: "cross_entropy"  # For regime classification
  
# Predictions
regimes:
  0: "Calm/Normal"
  1: "Volatility-Driven Risk-Off"
  2: "Liquidity Crisis"
  3: "Credit-Driven Selloff"
  4: "Rate-Driven Selloff"
  5: "Strong Inflow/Rally"
  6: "Technical Positioning/Dislocation" 
