# Configuration placeholder 

# Risk Scoring Models Configuration

# Common data parameters
data:
  max_encoder_length: 60  # Number of time steps used as encoder inputs
  max_prediction_length: 5  # Number of time steps to predict into future
  time_idx: "time_idx"  # Column name for time index
  group_ids:  # Column(s) for grouping data
    - "security_id"
    - "trade_type"
  target: "risk_score"  # Target variable to predict
  
  # Variables configuration
  categorical_variables:
    - "security_type"
    - "trade_type"
    - "regime"
  continuous_variables:
    - "price"
    - "volume"
    - "volatility"
    - "credit_spread"
    - "liquidity_metric"
    - "rate_change"
    - "trade_size"
    - "portfolio_exposure"
  static_variables:
    - "security_type"
    - "trade_type"
  time_varying_known_variables:
    - "time_idx"
    - "regime"
  time_varying_unknown_variables:
    - "price"
    - "volume"
    - "volatility"
    - "credit_spread"
    - "liquidity_metric"
    - "rate_change"
    - "trade_size"
    - "portfolio_exposure"

# N-BEATS model parameters
nbeats:
  num_blocks: 3
  num_block_layers: 4
  expansion_coefficient_length: 5
  trend_blocks: 2
  generic_blocks: 1
  backcast_loss_ratio: 0.1
  
  # Training parameters
  learning_rate: 0.001
  batch_size: 64
  max_epochs: 100
  early_stopping_patience: 10
  gradient_clip_val: 0.1
  
  # Loss function
  loss: "mse"  # For regression tasks

# DeepAR model parameters
deepar:
  hidden_size: 40
  rnn_layers: 2
  dropout: 0.1
  distribution: "StudentT"  # Distribution to use for likelihood loss
  
  # Training parameters
  learning_rate: 0.001
  batch_size: 64
  max_epochs: 100
  early_stopping_patience: 10
  gradient_clip_val: 0.1

# Meta-learner parameters
meta_learner:
  regime_weights:
    0: [0.5, 0.5]  # Calm/Normal: [nbeats_weight, deepar_weight]
    1: [0.3, 0.7]  # Volatility-Driven Risk-Off
    2: [0.2, 0.8]  # Liquidity Crisis
    3: [0.3, 0.7]  # Credit-Driven Selloff
    4: [0.4, 0.6]  # Rate-Driven Selloff
    5: [0.6, 0.4]  # Strong Inflow/Rally
    6: [0.5, 0.5]  # Technical Positioning/Dislocation
  
  # Adaptation parameters
  adaptation_rate: 0.1  # Rate at which to adapt weights based on recent performance
  confidence_window: 10  # Number of recent predictions to consider for confidence calculation 