"""Request and response models for AI Tasks Service API (moved)."""

from typing import List, Optional, Dict, Any
from uuid import UUID
from pydantic import BaseModel, Field

from .backlog_models import Epic


class TasksChatRequest(BaseModel):
    """Chat-style request for backlog generation or refinement."""

    project_id: UUID = Field(..., description="Project identifier")
    prompt_id: Optional[UUID] = Field(None, description="Conversation thread ID (omit for new conversation)")
    message: str = Field(..., description="User message (initial requirements or follow-up answer)")
    options: Optional[Dict[str, Any]] = Field(
        None,
        description="Optional parameters: top_k, similarity_threshold, max_iters",
    )


class ClarificationQuestion(BaseModel):
    """A clarification question generated by the system."""

    id: str = Field(..., description="Question identifier")
    text: str = Field(..., description="Question text")


class GeneratedBacklogBundle(BaseModel):
    """Generated backlog bundle with epics, tasks, and metadata."""

    prompt_id: UUID = Field(..., description="Conversation thread identifier")
    project_id: UUID = Field(..., description="Project identifier")
    epics: List[Epic] = Field(default_factory=list, description="Generated epics with tasks")
    assumptions: List[str] = Field(default_factory=list, description="Assumptions made during generation")
    risks: List[str] = Field(default_factory=list, description="Identified risks")
    score: float = Field(..., ge=0.0, le=1.0, description="Overall quality score")
    coverage_components: Optional[Dict[str, float]] = Field(
        None,
        description="Component scores: coverage, specificity, feasibility, duplication",
    )
    clarification_questions: Optional[List[ClarificationQuestion]] = Field(
        None,
        description="Questions to improve score (present if score < target)",
    )
    markdown_text: Optional[str] = Field(
        None,
        description="Markdown-formatted backlog for display",
    )


class EnhanceTaskRequest(BaseModel):
    """Request for enhancing a single task/epic with AI."""

    project_id: UUID = Field(..., description="Project identifier")
    item_id: str = Field(..., description="Epic or task identifier")
    item_type: str = Field(..., description='Item type: "epic" or "task"')
    current_content: dict = Field(
        ..., description="Current task/epic content (title, description, acceptance_criteria, etc.)"
    )
    parent_epic_content: Optional[dict] = Field(
        None, description="Parent epic full content if this is a task (id, title, description for context)"
    )


class EnhancedTask(BaseModel):
    """Enhanced task/epic returned by AI enhancement workflow."""

    item_id: str = Field(..., description="Epic or task identifier")
    title: str = Field(..., description="Enhanced title")
    description: str = Field(..., description="Enhanced detailed description")
    acceptance_criteria: List[str] = Field(
        ..., description="Enhanced acceptance criteria"
    )
    dependencies: Optional[List[str]] = Field(
        None, description="Task dependencies"
    )



