x-service-defaults: &service_defaults
  extra_hosts:
    - "host.docker.internal:host-gateway"

services:
  # Base image - builds automatically, never runs
  python-base:
    build:
      context: ./services/base
      dockerfile: Dockerfile
    image: python-service-base:latest
    command: ["true"]  # Exits immediately, only used for building
    restart: "no"


  postgres:
    <<: *service_defaults
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: requirementsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microservices_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d requirementsdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  neo4j:
    <<: *service_defaults
    build:
      context: ./services
      dockerfile: ./neo4j_baked/Dockerfile
    image: neo4j_baked:5.26.0
    container_name: neo4j_db
    restart: always
    environment:
      NEO4J_AUTH: ${NEO4J_USERNAME:-neo4j}/${NEO4J_PASSWORD:-neo4j123}
      NEO4J_initial_dbms_default__database: ${NEO4J_DATABASE:-neo4j}
      NEO4J_server_memory_heap_initial__size: ${NEO4J_HEAP_INITIAL:-1G}
      NEO4J_server_memory_heap_max__size: ${NEO4J_HEAP_MAX:-2G}
      NEO4J_server_memory_pagecache_size: ${NEO4J_PAGECACHE:-1G}
      NEO4J_dbms_security_procedures_unrestricted: "gds.*,apoc.*"
      NEO4J_dbms_security_procedures_allowlist: "gds.*,apoc.*"
      NEO4J_server_jvm_additional: "-XX:+ExitOnOutOfMemoryError -XX:MaxDirectMemorySize=4G"
      NEO4J_gds_validate__using__max__memory__estimation: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_import_file_use__neo4j__config: "true"
      NEO4J_server_directories_import: "/import"
      NEO4J_server_bolt_listen__address: "0.0.0.0:7687"
      NEO4J_server_http_listen__address: "0.0.0.0:7474"
      NEO4J_db_transaction_timeout: 60s
      OAI_KEY: ${OAI_KEY:-key}
      OAI_MODEL: ${OAI_MODEL:-gpt-4o}
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_config:/conf
      - ./e2e_tests/test_drift_search/infra:/import:ro
    networks:
      - microservices_network
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u ${NEO4J_USERNAME:-neo4j} -p ${NEO4J_PASSWORD:-neo4j123} 'RETURN 1;'"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  db-init-service:
    <<: *service_defaults
    build:
      context: ./services
      dockerfile: ./db_init_service/Dockerfile
    image: db_init_service:latest
    container_name: db_init_service
    ports:
      - "8001:8000"
    environment:
      - API_PORT=8000
    env_file:
      - docker-compose.env
    depends_on:
      python-base:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
    networks:
      - microservices_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  postgresdb-schema-init:
    <<: *service_defaults
    image: python:3.13-slim
    container_name: postgresdb_schema_init
    depends_on:
      db-init-service:
        condition: service_healthy
    env_file:
      - docker-compose.env
    networks:
      - microservices_network
    # Run once: initialize PostgreSQL schema via db-init-service endpoint
    command:
      - python
      - -c
      - |
          import os,time,json,hmac,hashlib,base64,urllib.request
          secret=os.environ.get('LOCAL_JWT_SECRET','')
          if not secret: raise SystemExit('LOCAL_JWT_SECRET not set')
          header={'alg':'HS256','typ':'JWT'}
          payload={'oid': os.environ.get('DEV_USER_OID','system'), 'preferred_username': os.environ.get('DEV_USERNAME','system@local'), 'roles': [], 'iat': int(time.time()), 'exp': int(time.time())+600}
          def b64url(d): return base64.urlsafe_b64encode(d).rstrip(b'=')
          seg=b'.'.join([b64url(json.dumps(header,separators=(',',':')).encode()), b64url(json.dumps(payload,separators=(',',':')).encode())])
          sig=b64url(hmac.new(secret.encode(), seg, hashlib.sha256).digest())
          token=(seg+b'.'+sig).decode()
          req=urllib.request.Request('http://db-init-service:8000/db/init', data=b'', method='POST', headers={'Authorization': f'Bearer {token}'})
          print('POST /db/init with Authorization header')
          with urllib.request.urlopen(req, timeout=60) as resp:
              print(resp.status, resp.read().decode())
    restart: "no"

  neo4j-maintenance-service:
    <<: *service_defaults
    build:
      context: ./services
      dockerfile: ./neo4j_maintanance_service/Dockerfile
    image: neo4j_maintenance_service:latest
    container_name: neo4j_maintenance_service
    ports:
      - "8002:8000"
    environment:
      - API_PORT=8000
    env_file:
      - docker-compose.env
    depends_on:
      python-base:
        condition: service_completed_successfully
      neo4j:
        condition: service_healthy
    networks:
      - microservices_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  neo4j-schema-init:
    <<: *service_defaults
    image: python:3.13-slim
    container_name: neo4j_schema_init
    depends_on:
      neo4j-maintenance-service:
        condition: service_healthy
    env_file:
      - docker-compose.env
    networks:
      - microservices_network
    # Run once: initialize Neo4j schema via maintenance service endpoint
    command:
      - python
      - -c
      - |
          import os,time,json,hmac,hashlib,base64,urllib.request
          secret=os.environ.get('LOCAL_JWT_SECRET','')
          if not secret: raise SystemExit('LOCAL_JWT_SECRET not set')
          header={'alg':'HS256','typ':'JWT'}
          payload={'oid': os.environ.get('DEV_USER_OID','system'), 'preferred_username': os.environ.get('DEV_USERNAME','system@local'), 'roles': [], 'iat': int(time.time()), 'exp': int(time.time())+600}
          def b64url(d): return base64.urlsafe_b64encode(d).rstrip(b'=')
          seg=b'.'.join([b64url(json.dumps(header,separators=(',',':')).encode()), b64url(json.dumps(payload,separators=(',',':')).encode())])
          sig=b64url(hmac.new(secret.encode(), seg, hashlib.sha256).digest())
          token=(seg+b'.'+sig).decode()
          req=urllib.request.Request('http://neo4j-maintenance-service:8000/init-neo4j', data=b'', method='POST', headers={'Authorization': f'Bearer {token}'})
          print('POST /init-neo4j with Authorization header')
          with urllib.request.urlopen(req, timeout=60) as resp:
              print(resp.status, resp.read().decode())
    restart: "no"

  neo4j-ingestion-service:
    <<: *service_defaults
    build:
      context: ./services
      dockerfile: ./neo4j_ingestion_service/Dockerfile
    container_name: neo4j_ingestion_service
    ports:
      - "8006:8000"
    environment:
      - API_PORT=8000
      - RAG_WORKSPACE_ROOT=/workspace/graphrag
    env_file:
      - docker-compose.env
    depends_on:
      neo4j-maintenance-service:
        condition: service_healthy
      neo4j-schema-init:
        condition: service_completed_successfully
    networks:
      - microservices_network
    volumes:
      - graphrag_workspace:/workspace
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  project-management-service:
    <<: *service_defaults
    build:
      context: ./services
      dockerfile: ./project_management_service/Dockerfile
    image: project_management_service:latest
    container_name: project_management_service
    ports:
      - "8003:8000"
    environment:
      - API_PORT=8000
    env_file:
      - docker-compose.env
    depends_on:
      python-base:
        condition: service_completed_successfully
      db-init-service:
        condition: service_healthy
      postgresdb-schema-init:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    networks:
      - microservices_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  ui-service:
    <<: *service_defaults
    build:
      context: ./services
      dockerfile: ./ui_service/Dockerfile
    image: ui_service:latest
    container_name: ui_service
    ports:
      - "8007:8000"
    environment:
      - API_PORT=8000
    env_file:
      - docker-compose.env
    depends_on:
      python-base:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
      project-management-service:
        condition: service_healthy
      mock-auth-service:
        condition: service_healthy
      gitlab-mock-service:
        condition: service_healthy
    networks:
      - microservices_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  document-processing-service:
    <<: *service_defaults
    build:
      context: ./services
      dockerfile: ./document_processing_service/Dockerfile
    container_name: document_processing_service
    ports:
      - "8004:8000"
    environment:
      - API_PORT=8000
    env_file:
      - docker-compose.env
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - microservices_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/celery"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  neo4j-retrieval-service:
    <<: *service_defaults
    build:
      context: ./services
      dockerfile: ./neo4j_retrieval_service/Dockerfile
    image: neo4j_retrieval_service:latest
    container_name: neo4j_retrieval_service
    depends_on:
      python-base:
        condition: service_completed_successfully
    ports:
      - "8008:8000"
    environment:
      - API_PORT=8000
    env_file:
      - docker-compose.env
    networks:
      - microservices_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  ai-requirements-service:
    <<: *service_defaults
    build:
      context: ./services
      dockerfile: ./ai_requirements_service/Dockerfile
    image: ai_requirements_service:latest
    container_name: ai_requirements_service
    ports:
      - "8009:8000"
    environment:
      - API_PORT=8000
    env_file:
      - docker-compose.env
    depends_on:
      python-base:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
      neo4j-retrieval-service:
        condition: service_healthy
    networks:
      - microservices_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  # Redis for Celery background tasks
  redis:
    <<: *service_defaults
    image: redis:7-alpine
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - microservices_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru

  # Azurite for Azure Blob Storage emulation
  azurite:
    <<: *service_defaults
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: azurite_storage
    ports:
      - "10000:10000"  # Blob storage
      - "10001:10001"  # Queue storage
      - "10002:10002"  # Table storage
    command: "azurite --skipApiVersionCheck --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0 --blobPort 10000 --queuePort 10001 --tablePort 10002 --loose --debug /workspace/debug.log"
    volumes:
      - azurite_data:/workspace
    networks:
      - microservices_network
    restart: unless-stopped
  
  # Optional: Admin tools for database management
  pgadmin:
    <<: *service_defaults
    image: dpage/pgadmin4:8
    container_name: pgadmin_tool
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - microservices_network
    profiles:
      - admin-tools
  
  # Optional: The mock Azure AD authentication server
  mock-auth-service:
    <<: *service_defaults
    build:
      context: ./services
      dockerfile: ./mock_auth_service/Dockerfile
    image: mock_auth_service:latest
    depends_on:
      python-base:
        condition: service_completed_successfully
    environment:
      - API_PORT=8000
      - ENABLE_HTTPS=true
    env_file:
      - docker-compose.env
    container_name: mock_auth_service
    ports:
      - "8005:8000"
    networks:
      - microservices_network
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  # Mock GitLab service for OAuth and API
  gitlab-mock-service:
    <<: *service_defaults
    build:
      context: ./services
      dockerfile: ./gitlab_mock_service/Dockerfile
    image: gitlab_mock_service:latest
    depends_on:
      python-base:
        condition: service_completed_successfully
    environment:
      - API_PORT=8000
    env_file:
      - docker-compose.env
    container_name: gitlab_mock_service
    ports:
      - "8011:8000"
    networks:
      - microservices_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  gitlab-client-service:
    <<: *service_defaults
    build:
      context: ./services
      dockerfile: ./gitlab_client_service/Dockerfile
    image: gitlab_client_service:latest
    container_name: gitlab_client_service
    ports:
      - "8012:8000"
    environment:
      - API_PORT=8000
    env_file:
      - docker-compose.env
    depends_on:
      python-base:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
      gitlab-mock-service:
        condition: service_healthy
    networks:
      - microservices_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  ai-tasks-service:
    <<: *service_defaults
    build:
      context: ./services
      dockerfile: ./ai_tasks_service/Dockerfile
    image: ai_tasks_service:latest
    container_name: ai_tasks_service
    ports:
      - "8013:8000"
    environment:
      - API_PORT=8000
    env_file:
      - docker-compose.env
    depends_on:
      python-base:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
      neo4j-retrieval-service:
        condition: service_healthy
      gitlab-client-service:
        condition: service_healthy
    networks:
      - microservices_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  openai-mock-service:
    <<: *service_defaults
    build:
      context: ./services
      dockerfile: ./openai_mock_service/Dockerfile
      args:
        - PRECACHE_MODELS=true # Set to true if it's the first time running the service
    container_name: openai_mock_service
    ports:
      - "8010:8000"
    env_file:
      - docker-compose.env
    networks:
      - microservices_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 2
      start_period: 10s
    restart: unless-stopped
    profiles:
      - e2e-tests

  gpt-oss-service:
    <<: *service_defaults
    build:
      context: ./services
      dockerfile: ./gpt_oss/Dockerfile
    container_name: gpt_oss_service
    ports:
      - "8010:11434"
    env_file:
      - docker-compose.env
    networks:
      - microservices_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/v1/models"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped
    profiles:
      - gpt-oss

  # End-to-end integration tests
  e2e-tests:
    <<: *service_defaults
    build:
      context: ./e2e_tests
      dockerfile: ./Dockerfile
    container_name: e2e_tests_runner
    environment:
      # Override service URLs to use internal docker network hostnames
      - PROJECT_MANAGEMENT_SERVICE_URL=http://project-management-service:8000
      - DOCUMENT_PROCESSING_URL=http://document-processing-service:8000
      - NEO4J_INGESTION_URL=http://neo4j-ingestion-service:8000
      - AZURE_AD_AUTHORITY=https://host.docker.internal:8005
      - INIT_DB_SERVICE_URL=http://db-init-service:8000
      - NEO4J_MAINTENANCE_URL=http://neo4j-maintenance-service:8000
      - UI_SERVICE_URL=http://ui-service:8000
      - AI_REQUIREMENTS_SERVICE_URL=http://ai-requirements-service:8000
      - NEO4J_RETRIEVAL_URL=http://neo4j-retrieval-service:8000
      - OPENAI_MOCK_URL=http://openai-mock-service:8000
      - GITLAB_BASE_URL=http://gitlab-mock-service:8000
      - GITLAB_INGESTION_BASE_URL=http://gitlab-client-service:8000
      - AI_TASKS_SERVICE_URL=http://ai-tasks-service:8000
    env_file:
      - docker-compose.env
    depends_on:
      postgres:
        condition: service_healthy
      neo4j:
        condition: service_healthy
      redis:
        condition: service_healthy
      db-init-service:
        condition: service_healthy
      neo4j-maintenance-service:
        condition: service_healthy
      neo4j-schema-init:
        condition: service_completed_successfully
      neo4j-ingestion-service:
        condition: service_healthy
      project-management-service:
        condition: service_healthy
      document-processing-service:
        condition: service_healthy
      mock-auth-service:
        condition: service_healthy
      gitlab-mock-service:
        condition: service_healthy
      gitlab-client-service:
        condition: service_healthy
      ai-tasks-service:
        condition: service_healthy
      openai-mock-service:
        condition: service_healthy
    networks:
      - microservices_network
    volumes:
      # Mount test results and logs for external access
      - ./e2e_tests/test-results:/e2e-tests/test-results
    restart: "no"  # Don't restart - tests should run once
    profiles:
      - e2e-tests  # Optional profile to run tests on demand

networks:
  microservices_network:
    driver: bridge
    name: git_epic_creator_network

volumes:
  postgres_data:
    driver: local
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local
  neo4j_config:
    driver: local
  redis_data:
    driver: local
  azurite_data:
    driver: local
  graphrag_workspace:
    driver: local