// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/favicon.ico": {
    params: {};
  };
  "/.well-known/appspecific/com.chrome.devtools.json": {
    params: {};
  };
  "/projects": {
    params: {};
  };
  "/projects/:projectId/requirements": {
    params: {
      "projectId": string;
    };
  };
  "/projects/:projectId/tasks": {
    params: {
      "projectId": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/favicon.ico" | "/.well-known/appspecific/com.chrome.devtools.json" | "/projects" | "/projects/:projectId/requirements" | "/projects/:projectId/tasks";
  };
  "./routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "./routes/favicon.ico.ts": {
    id: "routes/favicon.ico";
    page: "/favicon.ico";
  };
  "./routes/chrome-devtools.json.ts": {
    id: "routes/chrome-devtools.json";
    page: "/.well-known/appspecific/com.chrome.devtools.json";
  };
  "./routes/projects.tsx": {
    id: "routes/projects";
    page: "/projects";
  };
  "./routes/projects.$projectId.requirements.tsx": {
    id: "routes/projects.$projectId.requirements";
    page: "/projects/:projectId/requirements";
  };
  "./routes/projects.$projectId.tasks.tsx": {
    id: "routes/projects.$projectId.tasks";
    page: "/projects/:projectId/tasks";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/_index": typeof import("./src/./routes/_index.tsx");
  "routes/favicon.ico": typeof import("./src/./routes/favicon.ico.ts");
  "routes/chrome-devtools.json": typeof import("./src/./routes/chrome-devtools.json.ts");
  "routes/projects": typeof import("./src/./routes/projects.tsx");
  "routes/projects.$projectId.requirements": typeof import("./src/./routes/projects.$projectId.requirements.tsx");
  "routes/projects.$projectId.tasks": typeof import("./src/./routes/projects.$projectId.tasks.tsx");
};