#define PY_SSIZE_T_CLEAN
#include <Python.h>

#include "tree_sitter/parser.h"

// Generated by the vendored grammar.
// NOTE: This grammar exports an uppercased symbol name.
extern const TSLanguage *tree_sitter_COBOL(void);

static PyObject *py_language(PyObject *self, PyObject *args) {
  (void)self;
  (void)args;

  const TSLanguage *lang = tree_sitter_COBOL();
  if (lang == NULL) {
    PyErr_SetString(PyExc_RuntimeError, "tree_sitter_COBOL() returned NULL");
    return NULL;
  }

  // The capsule name MUST be exactly what py-tree-sitter expects.
  return PyCapsule_New((void *)lang, "tree_sitter.Language", NULL);
}

static PyMethodDef Methods[] = {
    {"language", (PyCFunction)py_language, METH_NOARGS,
     "Return a Tree-sitter Language capsule for COBOL."},
    {NULL, NULL, 0, NULL},
};

static struct PyModuleDef moduledef = {
    PyModuleDef_HEAD_INIT,
    "_binding",
    "Tree-sitter COBOL language capsule.",
    -1,
    Methods,
};

PyMODINIT_FUNC PyInit__binding(void) { return PyModule_Create(&moduledef); }
