[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "dis-orchestrator-service"
version = "0.1.0"
description = "Data Ingestion Service Orchestrator"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "httpx",
    "pydantic-settings",
    "python-dotenv",
    "azure-appconfiguration-provider",
    "azure-identity",
    "news-sentiment-common @ file:../../common"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-mock",
    "pytest-asyncio"
]

[tool.pytest.ini_options]
pythonpath = [
    "src"
]

[tool.setuptools.packages.find]
where = ["src"]
exclude = ["tests*"] 