# Trading Agent Configuration

# Agent identity
agent:
  name: "risk_analyzer_agent"
  version: "0.1.0"
  description: "Risk analysis agent for pre-trade risk scoring and market regime prediction"

# Agent behavior
behavior:
  # Memory configuration
  memory:
    short_term_capacity: 1000  # Number of items to keep in short-term memory
    long_term_enabled: true
    long_term_storage: "redis"  # redis or file
    
  # Decision making
  reasoning:
    # Risk scoring thresholds
    risk_thresholds:
      low: 30
      medium: 70
      high: 90
    
    # Confidence thresholds for decisions
    confidence_thresholds:
      low: 0.5
      medium: 0.7
      high: 0.9
      
    # Decision tree for risk analysis
    decision_rules:
      # Rule for high volatility regimes
      - name: "high_volatility_rule"
        condition: "regime in [1, 2]"  # Volatility-Driven Risk-Off or Liquidity Crisis
        action: "increase_risk_score"
        factor: 1.2
        
      # Rule for credit concerns
      - name: "credit_concern_rule"
        condition: "regime == 3"  # Credit-Driven Selloff
        action: "increase_risk_score"
        factor: 1.3
        
      # Rule for rate-sensitive securities
      - name: "rate_sensitive_rule"
        condition: "regime == 4 and security_type in ['government_bond', 'corporate_bond']"
        action: "increase_risk_score"
        factor: 1.5
        
      # Rule for favorable market conditions
      - name: "favorable_market_rule"
        condition: "regime == 5"  # Strong Inflow/Rally
        action: "decrease_risk_score"
        factor: 0.8
        
      # Rule for technical dislocations
      - name: "technical_dislocation_rule"
        condition: "regime == 6"  # Technical Positioning/Dislocation
        action: "apply_volatility_adjustment"
        adjustment: "dynamic"
        
  # Agent skills configuration
  skills:
    market_analysis:
      importance: 0.4
      data_sources: ["market_data", "regime_model"]
      
    security_analysis:
      importance: 0.3
      data_sources: ["security_data", "trade_history"]
      
    risk_score:
      importance: 0.5
      data_sources: ["risk_model", "meta_learner"]
      
    mitigation:
      importance: 0.2
      data_sources: ["rule_engine"]

# Monitoring and telemetry
monitoring:
  log_level: "INFO"
  metrics_enabled: true
  trace_decisions: true
  performance_tracking: true
  accuracy_evaluation: 
    enabled: true
    window_size: 100  # Evaluate accuracy over last N predictions 
